== CUIE - Assignment 2 - TimeControl

=== Bearbeitet von

Dalibor Simic

=== Abgabe

* Klasse 4iCa : Montag, 11.5.2020, 12:00 Uhr
* Klasse 4iCb : Donnerstag, 14.5.2020, 13:00 Uhr
* Die Abgabe erfolgt durch ein "Push" auf den Master-Branch Ihres GitHub-Repositories.

=== Anwendungskontext

Das TimeControl wurde als Arbeitszeit Tracker entworfen. Beispiel: Eintrag mit Caption "Project cuie Implementation" und  Uhrzeit 08:00 hinzufügen. Dann später um 14:00 einen neuen Eintrag hinufügen mit Caption "Project cuie Dokumentation".

=== Initiale Schritte

* Tragen Sie ihren Namen unter "Bearbeitet von" ein.
* Benennen Sie das Package `timecontrol` um. Verwenden Sie den GitHub-Account-Namen. (Via `Refactor -> Rename…`)
* Pushen Sie diese Änderungen sofort ins Git-Repository (z.B. via `VCS -> Commit… -> Commit & Push`)

=== Aufgabe: BusinessControl

Entwerfen und implementieren Sie das im Unterricht besprochene BusinessControl "TimeControl" auf Basis JavaFX.

* Benutzen Sie zur Umsetzung die vorgegebene Struktur mit Control, Skin und CSS.
* Beschreiben Sie im Abschnitt 'Anwendungskontext' (siehe oben) kurz für welchen spezifischen Zweck Ihr TimeControl entworfen wurde.

Es wird empfohlen, diese Aufgabe in einem 2-er Team zu bearbeiten.

=== Bewertung

* Für 2 Punkte muss das TimeControl unter 'Anwendungskontext' kurz beschrieben werden und die im Unterricht besprochenen Mindestanforderungen an ein BusinessControl erfüllt sein.
** die aktuelle Zeit kann angezeigt und verändert werden
** die Beschriftung kann definiert werden und wird geeignet visualisiert
** auf die Statuswechsel readOnly/editable, mandatory/optional, valid/invalid, konvertierbar/nicht konvertierbar wird dynamisch reagiert
** optimale Keyboardunterstützung inklusive Forgiving-Format
** optimale Maus-Unterstützung innerhalb des DropDownChoosers
* falls einer der initialen Schritte fehlt kann maximal 1 Punkt erreicht werden
* 0 Punkte gibt es
** falls das Projekt nicht komplierfähig ist
** falls der im Unterricht erarbeitete und jeweils auf dem AD zur Verfügung gestellte Stand nicht deutlich erkennbar verändert wurde
** für Plagiate
** falls kein aktiver Beitrag eines der beiden Teammitglieder an der Lösung erkennbar ist
** im Zweifelsfall wird ein Code-Walkthrough durchgeführt
* In Ausnahmefällen kann es dazu kommen, dass Teammitglieder unterschiedliche Punkte erhalten.


=== Bitte beachten Sie

* Falls Sie das Assignment zu zweit bearbeiten:
** tragen Sie beide Namen unter "Bearbeitet von" ein
** arbeiten Sie ausschliesslich in einem Repository
** falls sie beide Zugang zu diesem Repository wollen: tragen Sie die zweite Person als "Collaborator" ein (auf GitHub unter "Settings -> Manage access")
** löschen Sie das nicht benötigte Repository (auf GitHub unter "Settings")
** arbeiten Sie gemeinsam und gleichzeitig an den Aufgaben (Stichwort: Pair-Programming)
** https://www.it-agile.de/wissen/agiles-engineering/pair-programming/[Pair-Programming] heisst insbesondere, dass beide Teammitglieder zu gleichen Teilen aktiv in der Entwickler-Rolle sind. Einem Entwickler lediglich bei seiner Arbeit zuzuschauen ist kein Pair-Programming.
** das Aufteilen und separate Bearbeiten von Teil-Aufgaben ist nicht erwünscht
* Ausdrücklich erlaubt und erwünscht ist, dass Sie sich gegebenenfalls Hilfe holen.
Das Programmierzentrum ist geöffnet und Nachfragen werden zum Beispiel über den im Repository integrierten
Issue Tracker oder per Mail gerne beantwortet.


=== Bei Problemen mit dem IntelliJ-Setup

Es kommt immer wieder mal vor, dass der Setup des IntelliJ-Projekts nicht auf Anhieb funktioniert oder "plötzlich" nicht mehr funktioniert.

Sie brauchen in so einem Fall NICHT nochmal den Invitation-Link annehmen oder das Projekt via “Check out from Version Control” oder "git clone …" nochmal anlegen.

Statt dessen ist es am besten den IntelliJ-Setup neu generieren zu lassen. Dazu verwendet man den File `build.gradle`, der eine komplette und IDE-unabhängige Projektbeschreibung enthält.

Die einzelnen Schritte:

* Schliessen Sie alle geöffneten Projekte (`File -> Close Project`)
* Wählen Sie “OPEN”
* Es erscheint ein Finder-Fenster mit dem Sie zu ihrem Projekt navigieren.
* Dort wählen Sie den File `build.gradle` aus.
* Beim nächsten Dialog `Open as Project` wählen.
* In der "Project Structure" kontrollieren ob Java 13 ausgewählt ist (und dieser JDK JavaFX enthält).
* In den "Settings" ("Preferences" auf dem Mac) überprüfen, ob für Gradle als "Gradle JVM" der Project-SDK eingestellt ist.

Jetzt sollte der Projekt-Setup korrekt und  `DemoStarter` und `TimeControlTest` ausführbar sein.
